### ISSUE TITLE
Spec: Are implementations free to use their own hash code calculation

### ISSUE THREAD

**Issue by taqtiqa-mark** [dynatrace-oss/dynahist#14]
# Feature Request

## Summary

Are implementations free to use their own hash code calculation

## Feature Description

I suppose this is under the rubric of a specification.

**Comment by oertl** [comment]
@taqtiqa-mark, is this still relevant? Could you please explain this feature request in more detail?

**Comment by taqtiqa-mark** [comment]
Possibly.  I'm beginning working on a Rust port, and while I haven't got to the point of implementing hash related code, I do believe hash calculations in Rust are different.  I suppose I'm asking whether the hash calculations across languages need to be the same?
Does that make sense?

**Comment by oertl** [comment]
No, the `hashCode` implementations do not have to be identical. They are neither used as fingerprints nor for serialization. In Java, it is good practice to define `hashCode` when `equals` is defined. This is the main reason why there is a `hashCode` implementation for histograms.
