### ISSUE TITLE
histogram of 100 billion elements

### ISSUE THREAD

**Issue by jianshu93** [dynatrace-oss/dynahist#24]
Dear Dynahist team,

I have 100 billion elements (value between 0.75 and 1, can be any one, 4 digits, one element per line) stored in a file (100G), I want to plot a histogram of this file, bin size 0.005, starting from 0.75 to 1 and count number of elements fall in each bin. I did not find any other library/tool that can do the job. Exact counting is not possible because it requires a huge mount of memory. Since Dynahist is a Java library and I am not a java person at all. I think I have no choice but to do it myself using this library.

Want to hear your suggestions.

Thanks,

Jianshu

**Comment by oertl** [comment]
Hi Jianshu!

The values in the file can be easily summarized without loss of information using a plain hash table which maps every value to its frequency. Since the values have 4 digits, there are at most 10000 different values.

Otmar

**Comment by jianshu93** [comment]
Hello Otmar, 

Thanks for the suggestion, this is very helpful.

Jianshu
